version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: alinette
      POSTGRES_USER: alinette
      POSTGRES_PASSWORD: alinette
      PGDATA: /data/postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

volumes:
  postgres:
    driver: local

networks:
  postgres:
    driver: bridge

