version: "3"
name: alinette
services:
  postgres:
    container_name: postgres_alinette
    image: postgres:latest
    user: root
    environment:
      POSTGRES_DB: alinette
      POSTGRES_USER: alinette
      POSTGRES_PASSWORD: alinette
      PGDATA: /db/postgres

    ports:
      - "5432:5432"

    volumes:
      - db-postgres:/db/postgres
    # networks:
    #   - postgres
volumes:
  db-postgres:
    driver: local
# networks:
#   postgres:
#     driver: bridge
