version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: alinette
      POSTGRES_USER: alinette
      POSTGRES_PASSWORD: alinette
    ports:
      - "5432:5432"
    volumes:
      - alinette-data:/var/lib/postgresql/data

volumes:
  alinette-data:
    driver: local
    driver_opts:
      device: /mnt/d/database/alinette
