apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.ulimit: nofile=1048576:1048576
  creationTimestamp: "2023-11-06T01:33:19Z"
  labels:
    app: alinette-pod-database
  name: alinette-pod-database
spec:
  containers:
  - args:
    - start
    - --log
    - trace
    - --auth
    - --user
    - root
    - --pass
    - root
    - file:/db/
    image: docker.io/surrealdb/surrealdb:latest
    name: thirstymaxwell
    ports:
    - containerPort: 8000
      hostPort: 8080
    securityContext:
      runAsNonRoot: true
    tty: true
    volumeMounts:
    - mountPath: /db/
      name: alinette-database
  volumes:
  - hostPath:
      path: /mnt/d/surreal/alinette
      type: Directory
    name: alinette-database