/**
 * This code was generated by Builder.io.
 */
import { component$ } from "@builder.io/qwik";

export const MyComponent = component$((props) => {
	return (
		<div class="justify-center items-start flex gap-2.5">
			<img
				loading="lazy"
				srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/881246d8-4e3c-4df1-8b1f-168c5ffb0273?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/881246d8-4e3c-4df1-8b1f-168c5ffb0273?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/881246d8-4e3c-4df1-8b1f-168c5ffb0273?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/881246d8-4e3c-4df1-8b1f-168c5ffb0273?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/881246d8-4e3c-4df1-8b1f-168c5ffb0273?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/881246d8-4e3c-4df1-8b1f-168c5ffb0273?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/881246d8-4e3c-4df1-8b1f-168c5ffb0273?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/881246d8-4e3c-4df1-8b1f-168c5ffb0273?apiKey=2abb4ac878e0419aae6d537936d6d30b&"
				class="aspect-[15.91] object-cover object-center w-[175px]  fill-gray-400 overflow-hidden self-center shrink-0 my-auto"
			/>
			<div class="text-gray-400 text-base capitalize self-stretch">OR</div>
			<img
				loading="lazy"
				srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/59459432-7f94-423d-b1f9-339d712eadb9?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/59459432-7f94-423d-b1f9-339d712eadb9?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/59459432-7f94-423d-b1f9-339d712eadb9?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/59459432-7f94-423d-b1f9-339d712eadb9?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/59459432-7f94-423d-b1f9-339d712eadb9?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/59459432-7f94-423d-b1f9-339d712eadb9?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/59459432-7f94-423d-b1f9-339d712eadb9?apiKey=2abb4ac878e0419aae6d537936d6d30b&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/59459432-7f94-423d-b1f9-339d712eadb9?apiKey=2abb4ac878e0419aae6d537936d6d30b&"
				class="aspect-[15.91] object-cover object-center w-[175px]  fill-gray-400 overflow-hidden self-center shrink-0 my-auto"
			/>
		</div>
	);
});
